### ISSUE TITLE
Adding/editing an employee email problems

### ISSUE THREAD

**Issue by skippycrow** [skippycrow/T3_CS2450_001#65] opened 2021-12-13 23:04 UTC
When you add or edit an employee, regardless of what you type in the email field you get "email" as the value that is saved
![image](https://user-images.githubusercontent.com/70984355/145902976-92a38653-412f-45ff-b441-db952a37d982.png)

**Comment by ACast1** [comment] 2021-12-13 23:33
This will be fixed in this pull request https://github.com/skippycrow/T3_CS2450_001/pull/64

**Comment by ACast1** [comment] 2021-12-14 03:56
The pull request is merged and the issue is fixed for me. Close if you are no longer seeing this issue as well.

**Comment by zacryol** [comment] 2021-12-14 14:52
> The pull request is merged and the issue is fixed for me. Close if you are no longer seeing this issue as well.

It's possible to "link" a PR to an issue so that the issue is closed automatically when the PR gets merged. You can do it manually in the sidebar, or use some text like "resolves #[issue number]" in the PR description

**Closed by zacryol** 2021-12-14 14:52 UTC
